#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVoIP_Phone
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PEC")]
	public partial class DataClassesiVoIPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSetting(Setting instance);
    partial void UpdateSetting(Setting instance);
    partial void DeleteSetting(Setting instance);
    partial void InsertStateChangeEvent(StateChangeEvent instance);
    partial void UpdateStateChangeEvent(StateChangeEvent instance);
    partial void DeleteStateChangeEvent(StateChangeEvent instance);
    partial void InsertCallDetailRecord(CallDetailRecord instance);
    partial void UpdateCallDetailRecord(CallDetailRecord instance);
    partial void DeleteCallDetailRecord(CallDetailRecord instance);
    partial void InsertConsolidated(Consolidated instance);
    partial void UpdateConsolidated(Consolidated instance);
    partial void DeleteConsolidated(Consolidated instance);
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    partial void InsertAsteriskTable(AsteriskTable instance);
    partial void UpdateAsteriskTable(AsteriskTable instance);
    partial void DeleteAsteriskTable(AsteriskTable instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void InsertCurrStateInfo(CurrStateInfo instance);
    partial void UpdateCurrStateInfo(CurrStateInfo instance);
    partial void DeleteCurrStateInfo(CurrStateInfo instance);
    #endregion
		
		public DataClassesiVoIPDataContext() : 
				base(global::iVoIP_Phone.Properties.Settings.Default.PECConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesiVoIPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesiVoIPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesiVoIPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesiVoIPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
		
		public System.Data.Linq.Table<Workcode> Workcodes
		{
			get
			{
				return this.GetTable<Workcode>();
			}
		}
		
		public System.Data.Linq.Table<StateChangeEvent> StateChangeEvents
		{
			get
			{
				return this.GetTable<StateChangeEvent>();
			}
		}
		
		public System.Data.Linq.Table<CallDetailRecord> CallDetailRecords
		{
			get
			{
				return this.GetTable<CallDetailRecord>();
			}
		}
		
		public System.Data.Linq.Table<Consolidated> Consolidateds
		{
			get
			{
				return this.GetTable<Consolidated>();
			}
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
		
		public System.Data.Linq.Table<AsteriskTable> AsteriskTables
		{
			get
			{
				return this.GetTable<AsteriskTable>();
			}
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<CurrStateInfo> CurrStateInfos
		{
			get
			{
				return this.GetTable<CurrStateInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
	public partial class Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _extension;
		
		private int _Port;
		
		private bool _AAFlag;
		
		private bool _CFBFlag;
		
		private string _CFBNumber;
		
		private bool _CFNRFlag;
		
		private string _CFNRNumber;
		
		private bool _CFUFlag;
		
		private string _CFUNumber;
		
		private bool _DNDFlag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnextensionChanging(string value);
    partial void OnextensionChanged();
    partial void OnPortChanging(int value);
    partial void OnPortChanged();
    partial void OnAAFlagChanging(bool value);
    partial void OnAAFlagChanged();
    partial void OnCFBFlagChanging(bool value);
    partial void OnCFBFlagChanged();
    partial void OnCFBNumberChanging(string value);
    partial void OnCFBNumberChanged();
    partial void OnCFNRFlagChanging(bool value);
    partial void OnCFNRFlagChanged();
    partial void OnCFNRNumberChanging(string value);
    partial void OnCFNRNumberChanged();
    partial void OnCFUFlagChanging(bool value);
    partial void OnCFUFlagChanged();
    partial void OnCFUNumberChanging(string value);
    partial void OnCFUNumberChanged();
    partial void OnDNDFlagChanging(bool value);
    partial void OnDNDFlagChanged();
    #endregion
		
		public Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extension", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				if ((this._extension != value))
				{
					this.OnextensionChanging(value);
					this.SendPropertyChanging();
					this._extension = value;
					this.SendPropertyChanged("extension");
					this.OnextensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int NOT NULL")]
		public int Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AAFlag", DbType="Bit NOT NULL")]
		public bool AAFlag
		{
			get
			{
				return this._AAFlag;
			}
			set
			{
				if ((this._AAFlag != value))
				{
					this.OnAAFlagChanging(value);
					this.SendPropertyChanging();
					this._AAFlag = value;
					this.SendPropertyChanged("AAFlag");
					this.OnAAFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFBFlag", DbType="Bit NOT NULL")]
		public bool CFBFlag
		{
			get
			{
				return this._CFBFlag;
			}
			set
			{
				if ((this._CFBFlag != value))
				{
					this.OnCFBFlagChanging(value);
					this.SendPropertyChanging();
					this._CFBFlag = value;
					this.SendPropertyChanged("CFBFlag");
					this.OnCFBFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFBNumber", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CFBNumber
		{
			get
			{
				return this._CFBNumber;
			}
			set
			{
				if ((this._CFBNumber != value))
				{
					this.OnCFBNumberChanging(value);
					this.SendPropertyChanging();
					this._CFBNumber = value;
					this.SendPropertyChanged("CFBNumber");
					this.OnCFBNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFNRFlag", DbType="Bit NOT NULL")]
		public bool CFNRFlag
		{
			get
			{
				return this._CFNRFlag;
			}
			set
			{
				if ((this._CFNRFlag != value))
				{
					this.OnCFNRFlagChanging(value);
					this.SendPropertyChanging();
					this._CFNRFlag = value;
					this.SendPropertyChanged("CFNRFlag");
					this.OnCFNRFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFNRNumber", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CFNRNumber
		{
			get
			{
				return this._CFNRNumber;
			}
			set
			{
				if ((this._CFNRNumber != value))
				{
					this.OnCFNRNumberChanging(value);
					this.SendPropertyChanging();
					this._CFNRNumber = value;
					this.SendPropertyChanged("CFNRNumber");
					this.OnCFNRNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFUFlag", DbType="Bit NOT NULL")]
		public bool CFUFlag
		{
			get
			{
				return this._CFUFlag;
			}
			set
			{
				if ((this._CFUFlag != value))
				{
					this.OnCFUFlagChanging(value);
					this.SendPropertyChanging();
					this._CFUFlag = value;
					this.SendPropertyChanged("CFUFlag");
					this.OnCFUFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFUNumber", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CFUNumber
		{
			get
			{
				return this._CFUNumber;
			}
			set
			{
				if ((this._CFUNumber != value))
				{
					this.OnCFUNumberChanging(value);
					this.SendPropertyChanging();
					this._CFUNumber = value;
					this.SendPropertyChanged("CFUNumber");
					this.OnCFUNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNDFlag", DbType="Bit NOT NULL")]
		public bool DNDFlag
		{
			get
			{
				return this._DNDFlag;
			}
			set
			{
				if ((this._DNDFlag != value))
				{
					this.OnDNDFlagChanging(value);
					this.SendPropertyChanging();
					this._DNDFlag = value;
					this.SendPropertyChanged("DNDFlag");
					this.OnDNDFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Workcodes")]
	public partial class Workcode
	{
		
		private int _ID;
		
		private string _WORKCODE1;
		
		public Workcode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="WORKCODE", Storage="_WORKCODE1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string WORKCODE1
		{
			get
			{
				return this._WORKCODE1;
			}
			set
			{
				if ((this._WORKCODE1 != value))
				{
					this._WORKCODE1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StateChangeEvents")]
	public partial class StateChangeEvent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Exten;
		
		private string _State;
		
		private string _Reason;
		
		private string _Datetime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnExtenChanging(string value);
    partial void OnExtenChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnDatetimeChanging(string value);
    partial void OnDatetimeChanged();
    #endregion
		
		public StateChangeEvent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exten", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Exten
		{
			get
			{
				return this._Exten;
			}
			set
			{
				if ((this._Exten != value))
				{
					this.OnExtenChanging(value);
					this.SendPropertyChanging();
					this._Exten = value;
					this.SendPropertyChanged("Exten");
					this.OnExtenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datetime", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Datetime
		{
			get
			{
				return this._Datetime;
			}
			set
			{
				if ((this._Datetime != value))
				{
					this.OnDatetimeChanging(value);
					this.SendPropertyChanging();
					this._Datetime = value;
					this.SendPropertyChanged("Datetime");
					this.OnDatetimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CallDetailRecord")]
	public partial class CallDetailRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _source;
		
		private string _destination;
		
		private string _type;
		
		private string _start;
		
		private string _answer;
		
		private string _endtime;
		
		private int _duration;
		
		private string _disposition;
		
		private string _workcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnsourceChanging(string value);
    partial void OnsourceChanged();
    partial void OndestinationChanging(string value);
    partial void OndestinationChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnstartChanging(string value);
    partial void OnstartChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    partial void OnendtimeChanging(string value);
    partial void OnendtimeChanged();
    partial void OndurationChanging(int value);
    partial void OndurationChanged();
    partial void OndispositionChanging(string value);
    partial void OndispositionChanged();
    partial void OnworkcodeChanging(string value);
    partial void OnworkcodeChanged();
    #endregion
		
		public CallDetailRecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this.OnsourceChanging(value);
					this.SendPropertyChanging();
					this._source = value;
					this.SendPropertyChanged("source");
					this.OnsourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string destination
		{
			get
			{
				return this._destination;
			}
			set
			{
				if ((this._destination != value))
				{
					this.OndestinationChanging(value);
					this.SendPropertyChanging();
					this._destination = value;
					this.SendPropertyChanged("destination");
					this.OndestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string start
		{
			get
			{
				return this._start;
			}
			set
			{
				if ((this._start != value))
				{
					this.OnstartChanging(value);
					this.SendPropertyChanging();
					this._start = value;
					this.SendPropertyChanged("start");
					this.OnstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this.OnanswerChanging(value);
					this.SendPropertyChanging();
					this._answer = value;
					this.SendPropertyChanged("answer");
					this.OnanswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this.OnendtimeChanging(value);
					this.SendPropertyChanging();
					this._endtime = value;
					this.SendPropertyChanged("endtime");
					this.OnendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int NOT NULL")]
		public int duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disposition", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string disposition
		{
			get
			{
				return this._disposition;
			}
			set
			{
				if ((this._disposition != value))
				{
					this.OndispositionChanging(value);
					this.SendPropertyChanging();
					this._disposition = value;
					this.SendPropertyChanged("disposition");
					this.OndispositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string workcode
		{
			get
			{
				return this._workcode;
			}
			set
			{
				if ((this._workcode != value))
				{
					this.OnworkcodeChanging(value);
					this.SendPropertyChanging();
					this._workcode = value;
					this.SendPropertyChanged("workcode");
					this.OnworkcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Consolidated")]
	public partial class Consolidated : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Extension;
		
		private string _LoginTime;
		
		private string _LogoutTime;
		
		private string _TotalLoginTime;
		
		private string _TotalReadyTime;
		
		private string _TotalNtRdyTime;
		
		private string _TotalTalkTime;
		
		private string _TotalIdleTime;
		
		private string _TotalHoldTime;
		
		private string _TotalACWTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnLoginTimeChanging(string value);
    partial void OnLoginTimeChanged();
    partial void OnLogoutTimeChanging(string value);
    partial void OnLogoutTimeChanged();
    partial void OnTotalLoginTimeChanging(string value);
    partial void OnTotalLoginTimeChanged();
    partial void OnTotalReadyTimeChanging(string value);
    partial void OnTotalReadyTimeChanged();
    partial void OnTotalNtRdyTimeChanging(string value);
    partial void OnTotalNtRdyTimeChanged();
    partial void OnTotalTalkTimeChanging(string value);
    partial void OnTotalTalkTimeChanged();
    partial void OnTotalIdleTimeChanging(string value);
    partial void OnTotalIdleTimeChanged();
    partial void OnTotalHoldTimeChanging(string value);
    partial void OnTotalHoldTimeChanged();
    partial void OnTotalACWTimeChanging(string value);
    partial void OnTotalACWTimeChanged();
    #endregion
		
		public Consolidated()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTime", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LoginTime
		{
			get
			{
				return this._LoginTime;
			}
			set
			{
				if ((this._LoginTime != value))
				{
					this.OnLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LoginTime = value;
					this.SendPropertyChanged("LoginTime");
					this.OnLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoutTime", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LogoutTime
		{
			get
			{
				return this._LogoutTime;
			}
			set
			{
				if ((this._LogoutTime != value))
				{
					this.OnLogoutTimeChanging(value);
					this.SendPropertyChanging();
					this._LogoutTime = value;
					this.SendPropertyChanged("LogoutTime");
					this.OnLogoutTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalLoginTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalLoginTime
		{
			get
			{
				return this._TotalLoginTime;
			}
			set
			{
				if ((this._TotalLoginTime != value))
				{
					this.OnTotalLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalLoginTime = value;
					this.SendPropertyChanged("TotalLoginTime");
					this.OnTotalLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReadyTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalReadyTime
		{
			get
			{
				return this._TotalReadyTime;
			}
			set
			{
				if ((this._TotalReadyTime != value))
				{
					this.OnTotalReadyTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalReadyTime = value;
					this.SendPropertyChanged("TotalReadyTime");
					this.OnTotalReadyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalNtRdyTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalNtRdyTime
		{
			get
			{
				return this._TotalNtRdyTime;
			}
			set
			{
				if ((this._TotalNtRdyTime != value))
				{
					this.OnTotalNtRdyTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalNtRdyTime = value;
					this.SendPropertyChanged("TotalNtRdyTime");
					this.OnTotalNtRdyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTalkTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalTalkTime
		{
			get
			{
				return this._TotalTalkTime;
			}
			set
			{
				if ((this._TotalTalkTime != value))
				{
					this.OnTotalTalkTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalTalkTime = value;
					this.SendPropertyChanged("TotalTalkTime");
					this.OnTotalTalkTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalIdleTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalIdleTime
		{
			get
			{
				return this._TotalIdleTime;
			}
			set
			{
				if ((this._TotalIdleTime != value))
				{
					this.OnTotalIdleTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalIdleTime = value;
					this.SendPropertyChanged("TotalIdleTime");
					this.OnTotalIdleTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHoldTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalHoldTime
		{
			get
			{
				return this._TotalHoldTime;
			}
			set
			{
				if ((this._TotalHoldTime != value))
				{
					this.OnTotalHoldTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalHoldTime = value;
					this.SendPropertyChanged("TotalHoldTime");
					this.OnTotalHoldTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalACWTime", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TotalACWTime
		{
			get
			{
				return this._TotalACWTime;
			}
			set
			{
				if ((this._TotalACWTime != value))
				{
					this.OnTotalACWTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalACWTime = value;
					this.SendPropertyChanged("TotalACWTime");
					this.OnTotalACWTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Exten;
		
		private string _LoginTime;
		
		private int _totDialCalls;
		
		private int _totRcvCalls;
		
		private int _totAnsCalls;
		
		private double _PSL;
		
		private double _GSL;
		
		private System.TimeSpan _avgAnsSpeed;
		
		private System.TimeSpan _avgHandTime;
		
		private System.TimeSpan _avgTalkTime;
		
		private System.TimeSpan _totLoginDur;
		
		private System.TimeSpan _totTalkTime;
		
		private System.TimeSpan _totHoldTime;
		
		private System.TimeSpan _totNrdyTime;
		
		private System.TimeSpan _totACWTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnExtenChanging(string value);
    partial void OnExtenChanged();
    partial void OnLoginTimeChanging(string value);
    partial void OnLoginTimeChanged();
    partial void OntotDialCallsChanging(int value);
    partial void OntotDialCallsChanged();
    partial void OntotRcvCallsChanging(int value);
    partial void OntotRcvCallsChanged();
    partial void OntotAnsCallsChanging(int value);
    partial void OntotAnsCallsChanged();
    partial void OnPSLChanging(double value);
    partial void OnPSLChanged();
    partial void OnGSLChanging(double value);
    partial void OnGSLChanged();
    partial void OnavgAnsSpeedChanging(System.TimeSpan value);
    partial void OnavgAnsSpeedChanged();
    partial void OnavgHandTimeChanging(System.TimeSpan value);
    partial void OnavgHandTimeChanged();
    partial void OnavgTalkTimeChanging(System.TimeSpan value);
    partial void OnavgTalkTimeChanged();
    partial void OntotLoginDurChanging(System.TimeSpan value);
    partial void OntotLoginDurChanged();
    partial void OntotTalkTimeChanging(System.TimeSpan value);
    partial void OntotTalkTimeChanged();
    partial void OntotHoldTimeChanging(System.TimeSpan value);
    partial void OntotHoldTimeChanged();
    partial void OntotNrdyTimeChanging(System.TimeSpan value);
    partial void OntotNrdyTimeChanged();
    partial void OntotACWTimeChanging(System.TimeSpan value);
    partial void OntotACWTimeChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exten", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Exten
		{
			get
			{
				return this._Exten;
			}
			set
			{
				if ((this._Exten != value))
				{
					this.OnExtenChanging(value);
					this.SendPropertyChanging();
					this._Exten = value;
					this.SendPropertyChanged("Exten");
					this.OnExtenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTime", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LoginTime
		{
			get
			{
				return this._LoginTime;
			}
			set
			{
				if ((this._LoginTime != value))
				{
					this.OnLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LoginTime = value;
					this.SendPropertyChanged("LoginTime");
					this.OnLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totDialCalls", DbType="Int NOT NULL")]
		public int totDialCalls
		{
			get
			{
				return this._totDialCalls;
			}
			set
			{
				if ((this._totDialCalls != value))
				{
					this.OntotDialCallsChanging(value);
					this.SendPropertyChanging();
					this._totDialCalls = value;
					this.SendPropertyChanged("totDialCalls");
					this.OntotDialCallsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totRcvCalls", DbType="Int NOT NULL")]
		public int totRcvCalls
		{
			get
			{
				return this._totRcvCalls;
			}
			set
			{
				if ((this._totRcvCalls != value))
				{
					this.OntotRcvCallsChanging(value);
					this.SendPropertyChanging();
					this._totRcvCalls = value;
					this.SendPropertyChanged("totRcvCalls");
					this.OntotRcvCallsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totAnsCalls", DbType="Int NOT NULL")]
		public int totAnsCalls
		{
			get
			{
				return this._totAnsCalls;
			}
			set
			{
				if ((this._totAnsCalls != value))
				{
					this.OntotAnsCallsChanging(value);
					this.SendPropertyChanging();
					this._totAnsCalls = value;
					this.SendPropertyChanged("totAnsCalls");
					this.OntotAnsCallsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSL", DbType="Float NOT NULL")]
		public double PSL
		{
			get
			{
				return this._PSL;
			}
			set
			{
				if ((this._PSL != value))
				{
					this.OnPSLChanging(value);
					this.SendPropertyChanging();
					this._PSL = value;
					this.SendPropertyChanged("PSL");
					this.OnPSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSL", DbType="Float NOT NULL")]
		public double GSL
		{
			get
			{
				return this._GSL;
			}
			set
			{
				if ((this._GSL != value))
				{
					this.OnGSLChanging(value);
					this.SendPropertyChanging();
					this._GSL = value;
					this.SendPropertyChanged("GSL");
					this.OnGSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avgAnsSpeed", DbType="Time NOT NULL")]
		public System.TimeSpan avgAnsSpeed
		{
			get
			{
				return this._avgAnsSpeed;
			}
			set
			{
				if ((this._avgAnsSpeed != value))
				{
					this.OnavgAnsSpeedChanging(value);
					this.SendPropertyChanging();
					this._avgAnsSpeed = value;
					this.SendPropertyChanged("avgAnsSpeed");
					this.OnavgAnsSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avgHandTime", DbType="Time NOT NULL")]
		public System.TimeSpan avgHandTime
		{
			get
			{
				return this._avgHandTime;
			}
			set
			{
				if ((this._avgHandTime != value))
				{
					this.OnavgHandTimeChanging(value);
					this.SendPropertyChanging();
					this._avgHandTime = value;
					this.SendPropertyChanged("avgHandTime");
					this.OnavgHandTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avgTalkTime", DbType="Time NOT NULL")]
		public System.TimeSpan avgTalkTime
		{
			get
			{
				return this._avgTalkTime;
			}
			set
			{
				if ((this._avgTalkTime != value))
				{
					this.OnavgTalkTimeChanging(value);
					this.SendPropertyChanging();
					this._avgTalkTime = value;
					this.SendPropertyChanged("avgTalkTime");
					this.OnavgTalkTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totLoginDur", DbType="Time NOT NULL")]
		public System.TimeSpan totLoginDur
		{
			get
			{
				return this._totLoginDur;
			}
			set
			{
				if ((this._totLoginDur != value))
				{
					this.OntotLoginDurChanging(value);
					this.SendPropertyChanging();
					this._totLoginDur = value;
					this.SendPropertyChanged("totLoginDur");
					this.OntotLoginDurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totTalkTime", DbType="Time NOT NULL")]
		public System.TimeSpan totTalkTime
		{
			get
			{
				return this._totTalkTime;
			}
			set
			{
				if ((this._totTalkTime != value))
				{
					this.OntotTalkTimeChanging(value);
					this.SendPropertyChanging();
					this._totTalkTime = value;
					this.SendPropertyChanged("totTalkTime");
					this.OntotTalkTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totHoldTime", DbType="Time NOT NULL")]
		public System.TimeSpan totHoldTime
		{
			get
			{
				return this._totHoldTime;
			}
			set
			{
				if ((this._totHoldTime != value))
				{
					this.OntotHoldTimeChanging(value);
					this.SendPropertyChanging();
					this._totHoldTime = value;
					this.SendPropertyChanged("totHoldTime");
					this.OntotHoldTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totNrdyTime", DbType="Time NOT NULL")]
		public System.TimeSpan totNrdyTime
		{
			get
			{
				return this._totNrdyTime;
			}
			set
			{
				if ((this._totNrdyTime != value))
				{
					this.OntotNrdyTimeChanging(value);
					this.SendPropertyChanging();
					this._totNrdyTime = value;
					this.SendPropertyChanged("totNrdyTime");
					this.OntotNrdyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totACWTime", DbType="Time NOT NULL")]
		public System.TimeSpan totACWTime
		{
			get
			{
				return this._totACWTime;
			}
			set
			{
				if ((this._totACWTime != value))
				{
					this.OntotACWTimeChanging(value);
					this.SendPropertyChanging();
					this._totACWTime = value;
					this.SendPropertyChanged("totACWTime");
					this.OntotACWTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AsteriskTable")]
	public partial class AsteriskTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ProxyIP;
		
		private int _Port;
		
		private string _ManagerUsername;
		
		private string _ManagerPassword;
		
		private int _ManagerPort;
		
		private string _Queue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnProxyIPChanging(string value);
    partial void OnProxyIPChanged();
    partial void OnPortChanging(int value);
    partial void OnPortChanged();
    partial void OnManagerUsernameChanging(string value);
    partial void OnManagerUsernameChanged();
    partial void OnManagerPasswordChanging(string value);
    partial void OnManagerPasswordChanged();
    partial void OnManagerPortChanging(int value);
    partial void OnManagerPortChanged();
    partial void OnQueueChanging(string value);
    partial void OnQueueChanged();
    #endregion
		
		public AsteriskTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProxyIP", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProxyIP
		{
			get
			{
				return this._ProxyIP;
			}
			set
			{
				if ((this._ProxyIP != value))
				{
					this.OnProxyIPChanging(value);
					this.SendPropertyChanging();
					this._ProxyIP = value;
					this.SendPropertyChanged("ProxyIP");
					this.OnProxyIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int NOT NULL")]
		public int Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerUsername", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ManagerUsername
		{
			get
			{
				return this._ManagerUsername;
			}
			set
			{
				if ((this._ManagerUsername != value))
				{
					this.OnManagerUsernameChanging(value);
					this.SendPropertyChanging();
					this._ManagerUsername = value;
					this.SendPropertyChanged("ManagerUsername");
					this.OnManagerUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerPassword", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ManagerPassword
		{
			get
			{
				return this._ManagerPassword;
			}
			set
			{
				if ((this._ManagerPassword != value))
				{
					this.OnManagerPasswordChanging(value);
					this.SendPropertyChanging();
					this._ManagerPassword = value;
					this.SendPropertyChanged("ManagerPassword");
					this.OnManagerPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerPort", DbType="Int NOT NULL")]
		public int ManagerPort
		{
			get
			{
				return this._ManagerPort;
			}
			set
			{
				if ((this._ManagerPort != value))
				{
					this.OnManagerPortChanging(value);
					this.SendPropertyChanging();
					this._ManagerPort = value;
					this.SendPropertyChanged("ManagerPort");
					this.OnManagerPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Queue", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Queue
		{
			get
			{
				return this._Queue;
			}
			set
			{
				if ((this._Queue != value))
				{
					this.OnQueueChanging(value);
					this.SendPropertyChanging();
					this._Queue = value;
					this.SendPropertyChanged("Queue");
					this.OnQueueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logins")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Extension;
		
		private string _Secret;
		
		private string _SystemType;
		
		private char _SystemRights;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnSecretChanging(string value);
    partial void OnSecretChanged();
    partial void OnSystemTypeChanging(string value);
    partial void OnSystemTypeChanged();
    partial void OnSystemRightsChanging(char value);
    partial void OnSystemRightsChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secret", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Secret
		{
			get
			{
				return this._Secret;
			}
			set
			{
				if ((this._Secret != value))
				{
					this.OnSecretChanging(value);
					this.SendPropertyChanging();
					this._Secret = value;
					this.SendPropertyChanged("Secret");
					this.OnSecretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemType", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string SystemType
		{
			get
			{
				return this._SystemType;
			}
			set
			{
				if ((this._SystemType != value))
				{
					this.OnSystemTypeChanging(value);
					this.SendPropertyChanging();
					this._SystemType = value;
					this.SendPropertyChanged("SystemType");
					this.OnSystemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemRights", DbType="NChar(1) NOT NULL")]
		public char SystemRights
		{
			get
			{
				return this._SystemRights;
			}
			set
			{
				if ((this._SystemRights != value))
				{
					this.OnSystemRightsChanging(value);
					this.SendPropertyChanging();
					this._SystemRights = value;
					this.SendPropertyChanged("SystemRights");
					this.OnSystemRightsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CurrStateInfo")]
	public partial class CurrStateInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Extension;
		
		private string _LoginTime;
		
		private string _LogoutTime;
		
		private bool _IsLogin;
		
		private bool _IsReady;
		
		private bool _OnCall;
		
		private bool _Idle;
		
		private bool _ACW;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnLoginTimeChanging(string value);
    partial void OnLoginTimeChanged();
    partial void OnLogoutTimeChanging(string value);
    partial void OnLogoutTimeChanged();
    partial void OnIsLoginChanging(bool value);
    partial void OnIsLoginChanged();
    partial void OnIsReadyChanging(bool value);
    partial void OnIsReadyChanged();
    partial void OnOnCallChanging(bool value);
    partial void OnOnCallChanged();
    partial void OnIdleChanging(bool value);
    partial void OnIdleChanged();
    partial void OnACWChanging(bool value);
    partial void OnACWChanged();
    #endregion
		
		public CurrStateInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTime", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string LoginTime
		{
			get
			{
				return this._LoginTime;
			}
			set
			{
				if ((this._LoginTime != value))
				{
					this.OnLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LoginTime = value;
					this.SendPropertyChanged("LoginTime");
					this.OnLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoutTime", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string LogoutTime
		{
			get
			{
				return this._LogoutTime;
			}
			set
			{
				if ((this._LogoutTime != value))
				{
					this.OnLogoutTimeChanging(value);
					this.SendPropertyChanging();
					this._LogoutTime = value;
					this.SendPropertyChanged("LogoutTime");
					this.OnLogoutTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogin", DbType="Bit NOT NULL")]
		public bool IsLogin
		{
			get
			{
				return this._IsLogin;
			}
			set
			{
				if ((this._IsLogin != value))
				{
					this.OnIsLoginChanging(value);
					this.SendPropertyChanging();
					this._IsLogin = value;
					this.SendPropertyChanged("IsLogin");
					this.OnIsLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReady", DbType="Bit NOT NULL")]
		public bool IsReady
		{
			get
			{
				return this._IsReady;
			}
			set
			{
				if ((this._IsReady != value))
				{
					this.OnIsReadyChanging(value);
					this.SendPropertyChanging();
					this._IsReady = value;
					this.SendPropertyChanged("IsReady");
					this.OnIsReadyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnCall", DbType="Bit NOT NULL")]
		public bool OnCall
		{
			get
			{
				return this._OnCall;
			}
			set
			{
				if ((this._OnCall != value))
				{
					this.OnOnCallChanging(value);
					this.SendPropertyChanging();
					this._OnCall = value;
					this.SendPropertyChanged("OnCall");
					this.OnOnCallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idle", DbType="Bit NOT NULL")]
		public bool Idle
		{
			get
			{
				return this._Idle;
			}
			set
			{
				if ((this._Idle != value))
				{
					this.OnIdleChanging(value);
					this.SendPropertyChanging();
					this._Idle = value;
					this.SendPropertyChanged("Idle");
					this.OnIdleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACW", DbType="Bit NOT NULL")]
		public bool ACW
		{
			get
			{
				return this._ACW;
			}
			set
			{
				if ((this._ACW != value))
				{
					this.OnACWChanging(value);
					this.SendPropertyChanging();
					this._ACW = value;
					this.SendPropertyChanged("ACW");
					this.OnACWChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
